* Essential key bindings
** Tumx-like frame splitting
Split windows like in Tmux (but without the prefix key.)

#+begin_src emacs-lisp
  (define-key evil-normal-state-map (kbd "C-w \"") 'split-window-below)
  (define-key evil-normal-state-map (kbd "C-w %") 'split-window-horizontally)
#+end_src

** Save with RET in normal mode
Save buffer when hitting RET in normal mode.

#+begin_src emacs-lisp
  (define-key evil-normal-state-map (kbd "<RET>") 'save-buffer)
#+end_src

And use RET to get out of editing and org-mode code block

#+begin_src emacs-lisp
  (evil-define-key 'normal org-src-mode-map (kbd "<RET>") 'org-edit-src-exit)
  (evil-define-key 'normal org-src-mode-map (kbd "<backspace>") 'org-edit-src-abort)
#+end_src
* Extensions
** TODO Hexl mode
** org-mode
*** Global Settings
**** Default ORG Directory
#+begin_src emacs-lisp
  (setq org-directory (concat (getenv "HOME") "/doc/org"))
#+end_src
*** Capture
    Capturing to default location
#+begin_src emacs-lisp
  (setq org-default-notes-file (concat org-directory "/notes.org"))
  (define-key evil-normal-state-map (kbd "SPC o c") 'org-capture)
  (define-key evil-normal-state-map (kbd "SPC o l") 'org-capture-goto-last-stored)
#+end_src

Add templates
#+begin_src emacs-lisp
  (setq org-capture-templates
        '(("t" "Todo" entry (file+headline (concat org-directory "/main.org")
                                           "In")
           "* TODO %^{Title} %^g\n%i%?\n%a\n%T")
          ("m" "M.A." entry (file+headline "~/src/thesis/plan.org"
                                           "In")
           "* TODO %^{Title}\n  %i%?\n  %a %T")
          ("w" "Work" entry (file+headline "~/Documents/work.org"
                                           "In")
           "* TODO %^{Title} %^g\n%i%?\n%a\n%T")))
#+end_src
*** Refiling
#+BEGIN_SRC emacs-lisp
  (setq org-refile-use-outline-path nil)
  (setq org-refile-targets '((nil . (:maxlevel . 3))))
  (setq org-outline-path-complete-in-steps nil)
#+END_SRC
*** DONE Citation setup
CLOSED: [2015-11-01 Sun 22:30]
**** Settings
Set the bibtex library, PDF program, and where the pdf files live.
#+begin_src emacs-lisp
  (setq org-link-abbrev-alist
        '(("bib" . "~/doc/lib/bib/main.bib::%s")))
  (setq reftex-default-bibliography '("/home/aleks/doc/lib/bib/main.bib"))
  (setq org-cite-link-pdf-program "mupdf")
  (setq org-cite-link-library "/home/aleks/doc/lib/%s.pdf")
#+end_src
**** Open PDFs in Library
#+begin_src emacs-lisp
  (defun open-pdf-from-library (path)
    "Open a pdf from a bibtex identifier. This is a hack, and should probably be
  done differently, but it works for now."
    (let* ((full-path (format org-cite-link-library path)))
      (if (file-exists-p full-path)
          (progn
            (start-process (format "%s-%s" org-cite-link-pdf-program path)
                           (format "*%s-process*" org-cite-link-pdf-program)
                           (format "/usr/bin/%s" org-cite-link-pdf-program)
                           full-path)
            (message "Viewing %s" path))
        (user-error (format "Couldn't find reference: '%s'" full-path)))))
#+end_src
**** Export commands
#+begin_src emacs-lisp
  (defun org-cite-link-export (command path desc format)
    (cond
     ((eq format 'latex) (format "\\%s{%s}" command path))))

  (org-add-link-type "autocite" 'open-pdf-from-library
                     (lambda (path desc format)
                       (org-cite-link-export "autocite" path desc format)))
  (org-add-link-type "textcite" 'open-pdf-from-library
                     (lambda (path desc format)
                       (org-cite-link-export "textcite" path desc format)))
#+end_src
**** Org & Reftex
#+begin_src emacs-lisp
  (defun org-mode-reftex-setup ()
    (message "Loading org mode reftex setup.")
    (load-library "reftex")
    (and (buffer-file-name) (file-exists-p (buffer-file-name))
         (progn ;enable auto-revert-mode to update reftex when bibtex file changes on disk
           (global-auto-revert-mode t)
           (reftex-parse-all)
           (reftex-set-cite-format
            '((?a . "[[autocite:%l][(%2a %y)]]")
              (?c . "[[textcite:%l][%2a (%y)]]"))))))

  (add-hook 'org-mode-hook 'org-mode-reftex-setup)
#+end_src
*** In-Line LaTeX
#+begin_src emacs-lisp
  (setq org-format-latex-options (plist-put org-format-latex-options :scale 1.5))
#+end_src
*** DONE LaTeX export
CLOSED: [2016-05-01 Sun 13:11]
**** LaTeX Process & Source Code Formatting
This uses minted and pygments to set source code written in Babel. The
=-shell-escape= option to XeLaTeX is a bit dangerous, so you shouldn't just
set arbitrary downloaded TeX-documents with it.
It also sets our TeX processing engine to XeLaTeX, which is as it should be.
#+begin_src emacs-lisp
  (require 'ox-latex)
  (add-to-list 'org-latex-packages-alist '("" "minted" nil))
  (setq org-latex-listings 'minted)
  (setq org-format-latex-options (plist-put org-format-latex-options :scale 1.5))
  (setq org-latex-pdf-process
        '("latexmk --shell-escape -xelatex %f"))
#+end_src
**** Preamble
The default preamble includes stuff that is not very compatible wiht XeLaTeX,
so we overwrite the it.
#+begin_src emacs-lisp
  (setq org-latex-default-packages-alist
        '(("" "fontspec" nil)
          ("" "csquotes" nil)
          ; Xelatex-compatible Emacs-default content of this variable
          ("" "graphicx" nil)
          ("" "longtable" nil)
          ("" "float" nil)
          ("" "wrapfig" nil)
          ("" "rotating" nil)
          ("normalem" "ulem" t)
          ("" "amsmath" t)
          ("" "marvosym" t)
          ("" "wasysym" t)
          ("" "amssymb" t)
          ("breaklinks,colorlinks,citecolor=blue" "hyperref" nil)
          "\\tolerance=1000"
          ; Polyglossia has to be loaded last for some reason I don't remember.
          ("" "polyglossia" nil)))
#+end_src
**** Quotes
Use the csquotes package (don't forget to put it in the default header.)
#+begin_src emacs-lisp
  (setq org-export-with-smart-quotes t)

  ; Add English csquotes style
  (add-to-list
   'org-export-smart-quotes-alist
   '("en"
     (primary-opening   :utf-8 "“"
                        :html "&ldquo;"
                        :latex "\\enquote{"
                        :texinfo "``")
     (primary-closing   :utf-8 "”"
                        :html "&rdquo;"
                        :latex "}"
                        :texinfo "''")
     (secondary-opening :utf-8 "‘"
                        :html "&lsquo;"
                        :latex "\\enquote*{"
                        :texinfo "`")
     (secondary-closing :utf-8 "’"
                        :html "&rsquo;"
                        :latex "}"
                        :texinfo "'")
     (apostrophe        :utf-8 "’"
                        :html "&rsquo;")))

  ; Add German csquotes style
  (add-to-list
   'org-export-smart-quotes-alist
   '("de"
    (primary-opening   :utf-8 "„"
                       :html "&bdquo;"
                       :latex "\\enquote{"
                       :texinfo "@quotedblbase{}")
    (primary-closing   :utf-8 "“"
                       :html "&ldquo;"
                       :latex "}"
                       :texinfo "@quotedblleft{}")
    (secondary-opening :utf-8 "‚"
                       :html "&sbquo;"
                       :latex "\\enquote*{"
                       :texinfo "@quotesinglbase{}")
    (secondary-closing :utf-8 "‘"
                       :html "&lsquo;"
                       :latex "}"
                       :texinfo "@quoteleft{}")
    (apostrophe        :utf-8 "’"
                       :html "&rsquo;")))
#+end_src
** whitespace
#+begin_src emacs-lisp
  (setq whitespace-style '(face trailing tabs tab-mark))
  (global-whitespace-mode)
#+end_src
** Haskell-Mode
Use stack by default.
#+begin_src emacs-lisp
(setq haskell-process-type 'stack-ghci)
#+end_src
** writeroom-mode
Increase the width of writeroom-mode, especially necessary in org-mode buffers.
#+begin_src emacs-lisp
  (setq writeroom-width '90)
#+end_src
