#!/usr/bin/bash


if [ -n "$DESKTOP_SESSION" ]; then
    eval $(gnome-keyring-daemon --start)
    export SSH_AUTH_SOCK
fi
setxkbmap -layout us,bg -variant dvorak, \
	-option caps:swapescape \
	-option compose:ralt \
	-option grp:rctrl_rshift_toggle

xsetroot -cursor_name left_ptr

emacs --daemon&
seafile-applet &
syncthing &
xcompmgr &
nitrogen --restore

dbus-launch xmonad > $HOME/.x-debug &
XMONADPID=$!

wait $XMONADPID
